### PR TITLE
Adaptation to declarative shadow dom

### PR DESCRIPTION
**Pull request by PatrykSzwer**
#7

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
If I remember correctly, to actually see anything in the app, I had to add organisations (by[ People](https://github.com/StarcounterApps/People) app, parent organisation and child), and add product by [Products](https://github.com/StarcounterApps/Products) app. 

About that slot names, I actually have a question. You're suggesting to change them on fully lower-case, but in examples in docs, app name starts with upper-cases: [docs](https://docs.starcounter.io/guides/web-apps/html-view-guidelines/)
So should I always set fully lower-case names, or You just suggesting it here and everywhere else should be the ones with upper-cases?

**Comment by tomalec** [comment]
@Mackiovello, @warpech Do I remember correctly that we agreed on fully lower case?

**Comment by Mackiovello** [comment]
> Do I remember correctly that we agreed on fully lower case?

Yes we did. I'll fix it in the docs

**Comment by PatrykSzwer** [comment]
Ok, I've changed it on full lower-case.

**Pull request merged**
